-- Run in Supabase SQL Editor if sync-user-data reports missing columns

ALTER TABLE supplements ADD COLUMN IF NOT EXISTS tracks_macros INTEGER DEFAULT 0;
ALTER TABLE supplements ADD COLUMN IF NOT EXISTS macro_calories DOUBLE PRECISION DEFAULT 0;
ALTER TABLE supplements ADD COLUMN IF NOT EXISTS macro_protein DOUBLE PRECISION DEFAULT 0;
ALTER TABLE supplements ADD COLUMN IF NOT EXISTS macro_fat DOUBLE PRECISION DEFAULT 0;
ALTER TABLE supplements ADD COLUMN IF NOT EXISTS macro_carbs DOUBLE PRECISION DEFAULT 0;
ALTER TABLE supplements ADD COLUMN IF NOT EXISTS allows_quantity INTEGER DEFAULT 0;

ALTER TABLE supplement_intakes ADD COLUMN IF NOT EXISTS quantity INTEGER DEFAULT 1;

ALTER TABLE user_profile ADD COLUMN IF NOT EXISTS ethnicity TEXT;
